test:
	g++ -o sobol_test sobol_const.cpp sobol.cpp sobol_test.cpp
	./sobol_test
demo:
	g++ -I/usr/include -o sobol_demo sobol_const.cpp sobol.cpp sobol_demo.cpp
	./sobol_demo
clean:
	rm -rf sobol_demo sobol_test